<?php

namespace Ndmb\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CollaboratorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollaboratorRepository extends EntityRepository
{
}
